version: '3.8'
services:

  php:
    build:
      context: ./app
      dockerfile: Dockerfile.php
    container_name: my-php-app
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db


  nginx:
    image: nginx:latest
    container_name: my-nginx-server
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    ports:
      - 80:80
    depends_on:
      - php


  db:
    image: mysql:latest
    container_name: my-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gabaytulong
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my-phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 8083:80


volumes:
  db-data:

networks:
  my-network:
